export const languageOptions = [
  { code: "US", country: "United States", language: "English" },
  { code: "CN", country: "China", language: "Chinese" },
  { code: "IN", country: "India", language: "Hindi / English" },
  { code: "BR", country: "Brazil", language: "Portuguese" },
  { code: "RU", country: "Russia", language: "Russian" },
  { code: "DE", country: "Germany", language: "German" },
  { code: "UK", country: "United Kingdom", language: "English" },
  { code: "FR", country: "France", language: "French" },
  { code: "JP", country: "Japan", language: "Japanese" },
  { code: "CA", country: "Canada", language: "English / French" },
  { code: "AU", country: "Australia", language: "English" },
  { code: "ZA", country: "South Africa", language: "English / Zulu / Xhosa" },
  { code: "MX", country: "Mexico", language: "Spanish" },
  { code: "IT", country: "Italy", language: "Italian" },
  { code: "ES", country: "Spain", language: "Spanish" },
  { code: "ID", country: "Indonesia", language: "Indonesian" },
  { code: "TR", country: "Turkey", language: "Turkish" },
  { code: "SA", country: "Saudi Arabia", language: "Arabic" },
  { code: "AR", country: "Argentina", language: "Spanish" },
  { code: "NG", country: "Nigeria", language: "English" },
  { code: "EG", country: "Egypt", language: "Arabic" },
];
